apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-dashboard-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-dashboard
  template:
    metadata:
      labels:
        app: test-dashboard
    spec:
      containers:
        - name: test-dashboard
          image: workreel.azurecr.io/test
          ports:
            - containerPort: 2000
          resources:
            requests:
              cpu: "30m"
            limits:
              cpu: "60m"
---
apiVersion: v1
kind: Service
metadata:
  name: test-dashboard-service
spec:
  ports:
    - port: 80
      targetPort: 2000
  selector:
    app: test-dashboard
