module.exports = {
    siteUrl: 'https://www.workreel.com',
    generateRobotsTxt: true,
    robotsTxtOptions: {
        policies: [{ userAgent: '*', allow: '/' }],
        additionalSitemaps: [`https://www.workreel.com/server-sitemap.xml`],
    },
    exclude: [
        '/dashboard',
        '/dashboard/employer',
        '/dashboard/feedback',
        '/dashboard/link',
        '/dashboard/subscription',
        '/dashboard/talent',
        '/forgot-password',
        '/media-e',
        '/complete-profile',
        '/complete-profile/congratulation',
        '/talent/complete-profile/about',
        '/talent/complete-profile/address',
        '/talent/complete-profile/congratulations',
        '/talent/complete-profile/education',
        '/talent/complete-profile/experience',
        '/talent/complete-profile/interest',
        '/talent/complete-profile/powertraits',
        '/talent/complete-profile/profilephoto',
        '/talent/complete-profile/reels',
        '/talent/complete-profile/vidtro',
        '/talent/find-job/desired-role',
        '/verify-profile',
    ],
}
