export const objectOfArray = [
    { image: '/static/logo-1.svg' },
    { image: '/static/logo-2.svg' },
    { image: '/static/logo-3.svg' },
    { image: '/static/logo-4.svg' },
    { image: '/static/logo-5.svg' },
    { image: '/static/logo-6.svg' },
    { image: '/static/logo-7.svg' },
    { image: '/static/logo-8.svg' },
    { image: '/static/logo-9.svg' },
    { image: '/static/logo-10.svg' },
    { image: '/static/logo-11.svg' },
    { image: '/static/logo-12.svg' },
    { image: '/static/logo-13.svg' },
    { image: '/static/logo-14.svg' },
    { image: '/static/logo-15.svg' },
    { image: '/static/logo-16.svg' },
    { image: '/static/logo-17.svg' },
    { image: '/static/logo-18.svg' },
    { image: '/static/logo-19.svg' },
    { image: '/static/logo-20.svg' },
    { image: '/static/logo-21.svg' },
    { image: '/static/logo-22.svg' },
]
