name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

env:
  REGISTRY_NAME: "workreel" # Replace with your ACR registry name
  RESOURCE_GROUP: "workreel" # Replace with your ACR resource group
  CLUSTER_NAME: "NewWorkreelCluster" # Replace with your Kubernetes cluster name
  NAMESPACE: "workreel" # Replace with your desired Kubernetes namespace

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        run: az acr login --name ${{ env.REGISTRY_NAME }}

      - name: Build and push Docker image
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY_NAME }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
        env:
          DOCKER_BUILDKIT: 1
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t ${{ env.REGISTRY_NAME }}.azurecr.io/my-app:${IMAGE_TAG} .
          docker push ${{ env.REGISTRY_NAME }}.azurecr.io/my-app:${IMAGE_TAG}

      - name: Set up Kubernetes CLI
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ./deployment.yaml -n ${{ env.NAMESPACE }}
