name: Azure Login

on:
  push:
    branches:
      - main

jobs:
  login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: |
            ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            ${{ secrets.TENANT }}
            ${{ secrets.SERVICE_PRINCIPAL }}
            ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}

      - name: Azure CLI script
        run: |
          # Your Azure CLI commands here
          az account show
          az resource list --query "[].{Name:name, Location:location, Type:type}"
